import { BUDGET_TOLERANCE } from '../backend/rules/budget';
import { supportKnowledge } from './support';

export const knowledge = [
  ...supportKnowledge,
  {
    id: 'gpu-naming-intel-arc',
    title: 'Intel Arc 显卡：芯片厂商与板卡品牌分开识别',
    category: 'recommendation',
    tags: [
      '显卡',
      'GPU',
      'Intel',
      '英特尔',
      'Arc',
      '锐炫',
      'B570',
      'ASRock',
      '华擎',
      '品牌',
      '型号',
    ],
    content:
      'Intel Arc 是 Intel 的显卡产品系列。ASRock 官方的 Intel Arc B570 Challenger 10GB OC 是区分芯片与板卡品牌的实例：图形芯片为 Intel Arc B570，板卡产品由 ASRock 华擎提供。完整型号中的 Intel 不能单凭词序当成板卡品牌；也不能据此将所有 Intel Arc 显卡都认作华擎产品。',
    source:
      'https://www.asrock.com/Graphics-Card/Intel/Intel%20Arc%20B570%20Challenger%2010GB%20OC/',
    checkedAt: '2026-09-16',
    kind: 'manufacturer',
  },
  {
    id: 'gpu-naming-nvidia-geforce',
    title: 'NVIDIA GeForce RTX：厂商与显卡产品系列的区别',
    category: 'recommendation',
    tags: [
      '显卡',
      'GPU',
      'NVIDIA',
      '英伟达',
      'GeForce',
      'RTX',
      '品牌',
      '型号',
      '系列',
    ],
    content:
      'GeForce RTX 属于 NVIDIA 的显卡产品系列。RTX 不是与 Intel、AMD 并列的芯片厂商名称；讨论这三家的游戏显卡时，应区分 Intel Arc、AMD Radeon RX 与 NVIDIA GeForce RTX。型号中的 GeForce RTX 标识不能单独确定具体板卡品牌。不同完整型号的规格应分别核对，不能仅凭系列名推断性能相同。',
    source: 'https://www.nvidia.com/en-us/geforce/graphics-cards/',
    checkedAt: '2026-09-16',
    kind: 'manufacturer',
  },
  {
    id: 'gpu-naming-amd-radeon',
    title: 'AMD Radeon RX：显卡系列与具体板卡型号分开识别',
    category: 'recommendation',
    tags: ['显卡', 'GPU', 'AMD', 'Radeon', 'RX', '品牌', '型号', '系列'],
    content:
      'Radeon RX 是 AMD 的显卡产品系列。AMD 表示这一图形芯片所属厂商，Radeon RX 表示显卡系列；完整商品名称还可能包含板卡品牌及该厂商的产品名称。用户说要 AMD 显卡时，需要区分芯片厂商偏好与指定某家板卡品牌，不能只凭 AMD 或 RX 字样确定具体板卡商品。',
    source: 'https://www.amd.com/en/products/graphics/desktops/radeon.html',
    checkedAt: '2026-09-16',
    kind: 'manufacturer',
  },
  {
    id: 'gpu-naming-catalog-boundary',
    title: '显卡名称识别与商品目录字段的边界',
    category: 'recommendation',
    tags: [
      '显卡',
      '芯片厂商',
      '板卡品牌',
      '完整型号',
      '商品查询',
      '品牌',
      '型号',
      'Intel',
      'AMD',
      'RTX',
    ],
    content:
      '芯片厂商、产品系列、板卡品牌和完整商品型号需要分开理解。确认具体商品时，应核对商品资料中的品牌、完整型号及已记录的规格，不能把型号首词直接当成板卡品牌，也不能忽略用户明确指定的品牌。知识中的型号实例仅用于解释名称，不表示本店已经收录该商品，也不能证明其价格或兼容性；这些信息需要另外核对当前商品资料和具体配置。',
    source: null,
    checkedAt: '2026-09-16',
    kind: 'project_policy',
  },
  {
    id: 'compat-memory',
    title: '内存代际与平台选择',
    category: 'compatibility',
    tags: ['内存', 'DDR4', 'DDR5', '主板', 'CPU'],
    content:
      'DDR4 与 DDR5 的电气特性和物理防呆不同，不能互插。CPU 支持两种内存不代表一块主板同时支持两种内存；必须按具体主板版本选择。检查内存代际、容量上限、条数与插槽数。高频套装标称速度不等于所有 CPU 和主板组合都保证达到的运行速度。',
    source:
      'https://www.kingston.com/en/blog/pc-performance/ddr-memory-generation-differences',
    checkedAt: '2026-09-07',
    kind: 'manufacturer',
  },
  {
    id: 'compat-cpu',
    title: '插槽与 BIOS 支持分开检查',
    category: 'compatibility',
    tags: ['CPU', '主板', 'BIOS', '插槽', '兼容'],
    content:
      'Intel 第十二代桌面处理器使用 LGA1700 平台。购买前应检查主板厂商的 CPU 支持清单及 BIOS 要求；插槽吻合只是必要条件。系统必须区分已确认支持、已确认冲突、缺少资料。不要将型号后缀相近视为同一个产品。',
    source:
      'https://www.intel.com/content/www/us/en/support/articles/000088143/processors/intel-core-processors.html',
    checkedAt: '2026-09-07',
    kind: 'manufacturer',
  },
  {
    id: 'compat-am5',
    title: 'AM5 平台规格实例',
    category: 'compatibility',
    tags: ['AMD', 'AM5', 'DDR5', '7600', 'CPU'],
    content:
      'AMD Ryzen 5 7600 的官方规格页列明 AM5 插槽与 DDR5 系统内存。该实例可用于理解 CPU、主板、内存之间的约束，不能据此推断任意 AM5 主板的出厂 BIOS 都已支持任意 AM5 CPU。商品资料导入时，应保留完整型号及具体主板支持证据。',
    source:
      'https://www.amd.com/en/support/downloads/drivers.html/processors/ryzen/ryzen-7000-series/amd-ryzen-5-7600.html',
    checkedAt: '2026-09-07',
    kind: 'manufacturer',
  },
  {
    id: 'compat-space',
    title: '机箱空间与供电审查流程',
    category: 'compatibility',
    tags: ['机箱', '电源', '显卡', '散热', '尺寸', '兼容'],
    content:
      '本项目检查主板板型、显卡长度和槽位厚度、风冷高度、内存与散热器间隙、电源尺寸和供电接口。厂家资料缺失的字段返回待确认，已知冲突禁止推荐。电源筛选优先采用对应显卡厂家建议功率；瞬时功耗及线材要求仍需按具体型号核对。',
    source: null,
    checkedAt: '2026-09-07',
    kind: 'project_policy',
  },
  {
    id: 'compat-preassembly-gate',
    title: '装机前兼容性：先阻断，装好后再验证',
    category: 'compatibility',
    tags: [
      '装机前',
      '兼容性',
      '核对顺序',
      '待确认',
      '主板',
      'CPU',
      '内存',
      '显卡',
      '电源',
      '机箱',
      '散热',
    ],
    content:
      '兼容性审核应在购买、装配前完成：先用商品的型号级规格筛掉已知冲突，避免拆装或退换成本。装配完成后的点亮、压力、温度和线材检查是验证环节，不能替代装机前审核，也不能把“未填规格”升级为通过。优先顺序是平台（CPU、主板、内存代际）→ 主板 CPU 支持清单与出厂 BIOS → 内存容量和插槽 → 机箱内显卡、散热、电源尺寸 → 显卡供电接口与电源建议功率 → 散热满载能力与风道。前面的项目决定后续配件是否还能使用，所以应先查；任何缺少厂家型号级证据的项目均保持待确认。',
    source: null,
    checkedAt: '2026-09-12',
    kind: 'project_policy',
  },
  {
    id: 'selection-cpu-platform',
    title: 'CPU 选型：先锁定平台，再确认主板支持与 BIOS',
    category: 'compatibility',
    tags: ['CPU', '处理器', '主板', '插槽', 'BIOS', '选型', '取舍'],
    content:
      'CPU 的选型作用是确定插槽和内存平台，并与用途、预算一起约束主板和散热器。先检查 CPU—主板插槽，是因为不匹配时其余部件没有继续比较的意义；插槽相同后仍必须以该主板厂家 CPU 支持清单和所需 BIOS 为准。性能、价格、发热和平台升级空间是常见取舍，但通用知识不能证明某一型号已经被该板支持，也不能推断出厂 BIOS 版本。资料不足时只能说明该组合待确认；CPU 标称 TDP 也不能代替整机功耗或散热满载结论。',
    source: null,
    checkedAt: '2026-09-12',
    kind: 'project_policy',
  },
  {
    id: 'selection-motherboard-platform',
    title: '主板选型：把平台、扩展与物理约束汇合',
    category: 'compatibility',
    tags: [
      '主板',
      'CPU',
      '内存',
      '机箱',
      'M.2',
      'BIOS',
      '板型',
      '选型',
      '取舍',
    ],
    content:
      '主板是 CPU、内存、硬盘、机箱和供电扩展的交汇点。解释选择时，可说明它满足当前已验证的插槽、内存代际、板型和所需接口约束；没有完整型号规格时不要把“有 M.2”“支持某 CPU”“最大内存多少”说成事实。优先核对主板，是因为平台代际、CPU 支持清单和 BIOS 会同时影响多件配件，后查会造成整套返工。常见取舍是把预算投入更多扩展、接口或升级空间，还是把预算留给更直接服务于用途的 CPU、GPU；取舍不是某个芯片组必然更快。',
    source: null,
    checkedAt: '2026-09-12',
    kind: 'project_policy',
  },
  {
    id: 'selection-memory-capacity-clearance',
    title: '内存选型：代际、容量、插槽与散热间隙分开确认',
    category: 'compatibility',
    tags: [
      '内存',
      'DDR4',
      'DDR5',
      '容量',
      '插槽',
      '高度',
      '散热',
      '主板',
      '选型',
      '取舍',
    ],
    content:
      '内存的选型作用是为当前用途提供容量，并匹配 CPU—主板确定的内存代际。先查代际、总容量、条数和主板插槽数，因为它们是可判定的基础约束；高条或带灯内存还要与散热器的内存净空一起核对。容量、频率、时序、条数、外观高度和未来扩容之间存在取舍：更多容量或更高规格可能占用更多预算和插槽，不能仅凭通用知识保证特定频率能稳定运行。缺少主板容量上限、内存高度或散热净空时，结果必须是待确认而非通过。',
    source: null,
    checkedAt: '2026-09-12',
    kind: 'project_policy',
  },
  {
    id: 'selection-gpu-fit-power',
    title: '显卡选型：用途预算之外，先核对机箱空间和供电',
    category: 'compatibility',
    tags: [
      'GPU',
      '显卡',
      '机箱',
      '厚度',
      '长度',
      '供电接口',
      '电源',
      '选型',
      '取舍',
    ],
    content:
      '显卡通常是游戏与 GPU 加速用途的重要预算投向，但具体选择仍受用户用途、预算、颜色和目录商品约束。先查显卡长度、厚度/槽位占用与机箱限制，再查厂家建议电源功率、供电接口类型及所需数量；这些是装得下、接得上的硬前提，不能由型号名称或显存容量推断。性能、显存、尺寸、噪声、价格和配色是常见取舍；更大的散热器或更高的功耗并不自动代表更适合当前机箱。任何一个尺寸、接口或建议功率缺失时，只能提示待确认。',
    source: null,
    checkedAt: '2026-09-12',
    kind: 'project_policy',
  },
  {
    id: 'selection-cooler-thermal-fit',
    title: '散热选型：扣具与空间先过关，热能力和风道另核对',
    category: 'compatibility',
    tags: [
      '散热',
      '风冷',
      '水冷',
      'CPU',
      '扣具',
      '高度',
      '内存',
      '风道',
      'TDP',
      '取舍',
    ],
    content:
      '散热器先要具备对应 CPU 插槽的扣具，并同时满足机箱高度或冷排位置、内存净空等物理条件；这些项目先查是因为装不上时散热性能比较没有价值。解释选择时应把静音、体积、内存兼容、价格和满载余量视为取舍。CPU 的标称 TDP 不是实际整机功耗，也不是某散热器一定足够的证明；散热满载能力还依赖 CPU 实际负载、机箱风道、环境和厂家规格。缺少扣具、尺寸、内存净空或风道资料时保留待确认，不凭“塔式更大”断言通过。',
    source: null,
    checkedAt: '2026-09-12',
    kind: 'project_policy',
  },
  {
    id: 'selection-case-clearance',
    title: '机箱选型：用完整物理边界收束整套配件',
    category: 'compatibility',
    tags: [
      '机箱',
      '板型',
      '显卡',
      '散热',
      '电源',
      '长度',
      '厚度',
      '高度',
      '空间',
      '取舍',
    ],
    content:
      '机箱决定主板板型、显卡长度与厚度、散热器高度或冷排位置、电源规格和长度能否同时容纳。它应在平台确定、显卡和散热候选明确后优先复核，因为一个空间限制可能同时推翻多件已选配件。体积、扩展、风道、噪声、外观和预算之间需要取舍；更大的机箱不自动保证所有组合通过。核对必须使用该机箱在对应安装条件下的厂家规格，不能把通用 ATX 或外观照片当作显卡厚度、冷排或电源余量的型号级证据。',
    source: null,
    checkedAt: '2026-09-12',
    kind: 'project_policy',
  },
  {
    id: 'selection-psu-power-connectors',
    title: '电源选型：功率建议与显卡供电线数量缺一不可',
    category: 'compatibility',
    tags: [
      '电源',
      'PSU',
      '显卡',
      '功率',
      '接口',
      '线材',
      'ATX',
      '机箱',
      '选型',
      '取舍',
    ],
    content:
      '电源的作用是同时满足整机的规格、机箱安装和显卡供电要求。先查显卡厂家建议功率，再查显卡所需的供电接口类型和数量、以及电源可用的原生接口数量；额定瓦数相同不代表线材配置相同。还应核对电源外形规格和长度是否适配机箱。价格、效率、噪声、线材管理、尺寸和余量是常见取舍，但不要以 CPU TDP、GPU 标称功耗或经验倍率代替厂家对具体显卡的建议。缺少电源长度或接口数量时保持待确认，不能因为瓦数足够就标为通过。',
    source: null,
    checkedAt: '2026-09-12',
    kind: 'project_policy',
  },
  {
    id: 'selection-storage-interface',
    title: '硬盘选型：先确认接口可用，再谈容量与速度取舍',
    category: 'compatibility',
    tags: [
      '硬盘',
      'SSD',
      'M.2',
      'NVMe',
      'SATA',
      '主板',
      '容量',
      '选型',
      '取舍',
    ],
    content:
      '硬盘的选型作用是按用途平衡容量、接口和预算。先核对主板是否提供所需接口及当前方案是否已占用相关位置，因为接口不匹配时容量和标称速度无法落地。容量、持续写入表现、散热需求、价格和未来扩展是常见取舍；不要把接口外形、PCIe 代际或标称顺序速度直接等同于实际软件体验。当前商品或主板没有完整接口资料时，应明确需要核实，不应把未记录的信息当成兼容结论。',
    source: null,
    checkedAt: '2026-09-12',
    kind: 'project_policy',
  },
  {
    id: 'recommend-budget',
    title: '预算硬边界与无解处理',
    category: 'recommendation',
    tags: ['预算', '价格', '便宜', '总价', '推荐'],
    content: `L 是满足当前型号、系列、品牌、颜色和购买方式约束的数据库最低完整兼容配置；H 是目录内满足约束的实际最高完整兼容配置（DIY 取完整兼容组合中的最高总价，整机取最贵合格整机售价），并不代表实测性能最强。预算低于 L 时仅展示八类完整的超预算参考，明确总价减预算，不能称符合预算或直接确认；预算高于 H 时展示目录最高参考并允许节省，但不得超过预算上界。L 到 H 之间差额绝对值默认不超过 ${BUDGET_TOLERANCE} 元，用户明确指定误差时按指定值执行，明确硬上限时收紧上界。DIY 总价按数据库八类配件现价相加，整机使用数据库整机售价；调价、替换后必须重算。显示器不计入主机预算。缺商品、已知兼容冲突、完整搜索确认的预算区间无解和搜索达到计算上限应分开说明，未知规格可作为待确认参考，不能当成已知冲突。`,
    source: null,
    checkedAt: '2026-09-07',
    kind: 'project_policy',
  },
  {
    id: 'recommend-game',
    title: '游戏用途如何分配预算',
    category: 'recommendation',
    tags: ['游戏', 'GPU', 'CPU', '推荐', 'CS2', '黑神话'],
    content:
      '先询问游戏名称和预算，先完成主机，不主动要求用户选择显示器。性能取舍需要依据具体游戏测试，不能认为所有游戏都只取决于显卡。当前候选排序给显卡较高预算权重，并保留 CPU、内存与完整配件的预算；权重仅是候选排序策略，不代表测得的游戏性能。主机确定后再讨论显示器预算、分辨率与刷新率。',
    source: null,
    checkedAt: '2026-09-07',
    kind: 'project_policy',
  },
  {
    id: 'recommend-work',
    title: '办公、创作与本地 AI 的追问策略',
    category: 'recommendation',
    tags: ['办公', '剪辑设计', '编程', '本地 AI', '显存', '推荐'],
    content:
      '办公需要区分文档网页与专业软件。创作需要软件、素材分辨率和项目规模。编程需要区分普通开发、虚拟机、容器和大型编译。本地 AI 需要模型规模、量化方式、推理或训练需求，并核查软件对 GPU 后端的支持。资料不完整时先给候选方案，不承诺能运行任意模型或保证特定生产效率。',
    source: null,
    checkedAt: '2026-09-07',
    kind: 'project_policy',
  },
  {
    id: 'recommend-prebuilt',
    title: '整机配置透明度',
    category: 'recommendation',
    tags: ['整机', '品牌', '内存', '电源', '推荐'],
    content:
      '整机需要关联八类完整配件。仅写容量或功率不能替代完整型号。整机按商家整机目录价推荐；配件行展示商家目录价，不代表整机拆件成交价。当前套餐价格包含 150 元装机服务，运费、系统授权与保修范围需由商家另行说明。',
    source: null,
    checkedAt: '2026-09-07',
    kind: 'project_policy',
  },
];
